// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://posfjtzhypekptobqiep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvc2ZqdHpoeXBla3B0b2JxaWVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODQyNTksImV4cCI6MjA2NTU2MDI1OX0.Jy3sHXupNbBUXn1u429ruJiF4pUBJaXu2epAZrc0tuQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);